---
meta:
  name:    openssl-source-code-resource
  release: OpenSSL tarball Concourse resource
  target:  gk-plat-devs
  url:     https://ci.gstack.io

  initial_version: "1.0.0"

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  image:
    name: harbor.ci.gstack.io/gstack/gk-ops
    registry:
      username: ((docker-registry-username))
      password: ((docker-registry-password))

  dockerhub:
    username:   ((docker-registry-username))
    password:   ((docker-registry-password))
    org:        gstack
    repository: (( concat "harbor.ci.gstack.io/" meta.dockerhub.org "/" meta.name ))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: eu-west-3
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:        gstackio
    repo:         openssl-source-code-resource
    branch:       master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#oss-pipelines-notifications"

groups:
  - name: (( grab meta.name ))
    jobs:
      - (( append ))
      - test

jobs:

  - name: test
    serial: true
    plan:
      - in_parallel:
          - { get: edge, passed: [ build ], trigger: true }
          - { get: git,  passed: [ build ] }
      - task: test-image
        image: edge
        config:
          platform: linux
          inputs:
            - name: git
          run:
            path: bash
            args:
              - -c
              - |
                set -ueo pipefail -x

                failure="false"

                version_family="0.9.8"
                old_version="0.9.8zg"

                latest_version_json=$(
                    jq --null-input \
                            --arg "family" "${version_family}" \
                            '{ "source": { "family": $family } }' \
                        | /opt/resource/check
                )
                latest_version=$(jq --raw-output '.[0].version' <<< "${latest_version_json}")

                if [[ ${latest_version} != ${version_family}* ]]; then
                    echo >&2 "FAIL: expected version to start with '${version_family}', but got '${latest_version}'."
                    failure="true"
                fi

                mkdir -p "artifact"
                jq --null-input \
                        --arg "version" "${old_version}" \
                        --arg "family" "${version_family}" \
                        '{
                          "version": { "version": $version },
                          "source": { "family": $family }
                        }' \
                    | /opt/resource/in "artifact"

                if [[ ! -f "artifact/openssl-${old_version}.tar.gz" ]]; then
                    >&2 echo "FAIL: expected to found a 'openssl-${old_version}.tar.gz' tarball, but got:"
                    >&2 ls -la "artifact/"
                    failure="true"
                fi

                if [[ ! -s "artifact/openssl-${old_version}.tar.gz" ]]; then
                    echo >&2 "FAIL: expected tarball not to be empty, but it's of 0 size."
                    >&2 ls -la "artifact/"
                    failure="true"
                fi

                mkdir -p "artifact"
                jq --null-input \
                        --arg "version" "${latest_version}" \
                        --arg "family" "${version_family}" \
                        '{
                          "version": { "version": $version },
                          "source": { "family": $family }
                        }' \
                    | /opt/resource/in "artifact"

                if [[ ! -f "artifact/openssl-${latest_version}.tar.gz" ]]; then
                    >&2 echo "FAIL: expected to found a 'openssl-${latest_version}.tar.gz' tarball, but got:"
                    >&2 ls -la "artifact/"
                    failure="true"
                fi

                if [[ ! -s "artifact/openssl-${latest_version}.tar.gz" ]]; then
                    echo >&2 "FAIL: expected tarball not to be empty, but it's of 0 size."
                    >&2 ls -la "artifact/"
                    failure="true"
                fi



                version_family="1.1.1"
                old_version="1.1.1q"

                latest_version_json=$(
                    jq --null-input \
                            --arg "family" "${version_family}" \
                            '{ "source": { "family": $family } }' \
                        | /opt/resource/check
                )
                latest_version=$(jq --raw-output '.[0].version' <<< "${latest_version_json}")

                if [[ ${latest_version} != ${version_family}* ]]; then
                    echo >&2 "FAIL: expected version to start with '${version_family}', but got '${latest_version}'."
                    failure="true"
                fi

                mkdir "old"
                jq --null-input \
                        --arg "version" "${old_version}" \
                        --arg "family" "${version_family}" \
                        '{
                          "version": { "version": $version },
                          "source": { "family": $family }
                        }' \
                    | /opt/resource/in "old"

                if [[ ! -f "old/openssl-${old_version}.tar.gz" ]]; then
                    >&2 echo "FAIL: expected to found a 'openssl-${old_version}.tar.gz' tarball, but got:"
                    >&2 ls -la "old/"
                    failure="true"
                fi

                if [[ ! -s "old/openssl-${old_version}.tar.gz" ]]; then
                    echo >&2 "FAIL: expected tarball not to be empty, but it's of 0 size."
                    >&2 ls -la "old/"
                    failure="true"
                fi

                mkdir "current"
                jq --null-input \
                        --arg "version" "${latest_version}" \
                        --arg "family" "${version_family}" \
                        '{
                          "version": { "version": $version },
                          "source": { "family": $family }
                        }' \
                    | /opt/resource/in "current"

                if [[ ! -f "current/openssl-${latest_version}.tar.gz" ]]; then
                    >&2 echo "FAIL: expected to found a 'openssl-${latest_version}.tar.gz' tarball, but got:"
                    >&2 ls -la "current/"
                    failure="true"
                fi

                if [[ ! -s "current/openssl-${latest_version}.tar.gz" ]]; then
                    echo >&2 "FAIL: expected tarball not to be empty, but it's of 0 size."
                    >&2 ls -la "current/"
                    failure="true"
                fi

                if [[ ${failure} == true ]]; then
                    exit 1
                fi
                exit 0

        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     (( grab meta.slack.fail_text ))

  - name: pre
    plan:
      - (( inline ))
      - in_parallel:
          - (( merge on get ))
          - { get: edge, passed: [ (( replace )), test ] }
          - { get: git,  passed: [ (( replace )), test ] }

  - name: promote
    plan:
      - (( inline ))
      - {} # in_parallel:
      - {} # task: release
      - {} # load_var: version
      - {} # put: latest

      - task: update-dockerhub-readme
        params:
          # Use DockerHub credentials and not our private registry
          DOCKERHUB_USERNAME:   ((dockerhub-username))
          DOCKERHUB_PASSWORD:   ((dockerhub-password))
          DOCKERHUB_REPOSITORY: (( concat meta.dockerhub.org "/" meta.name ))

      - (( insert after 1 )) # insert after “task: release”
      - task: append-usage
        image: image
        config:
          platform: linux
          inputs:  [ name: gh, name: version ]
          outputs: [ name: gh ]
          run:
            path: bash
            args:
              - -c
              - |
                set -ueo pipefail
                cat >> gh/notes.md <<EOF

                ### Usage

                \`\`\`yaml
                resource_types:
                  - name: bosh-config
                    type: registry-image
                    source:
                      repository: ${DOCKERHUB_REPOSITORY}
                      tag: "$(< version/number)"
                \`\`\`
                EOF
        params:
          DOCKERHUB_REPOSITORY: (( concat "gstack/" meta.name ))

resources:

  - name: git
    check_every: 24h
    webhook_token: ((concourse-webhook-token))

  - name: git-pull-requests
    check_every: 24h
    webhook_token: ((concourse-webhook-token))

  - name: version
    icon: github
    source:
      bucket:            (( prune ))
      region_name:       (( prune ))
      key:               (( prune ))
      access_key_id:     (( prune ))
      secret_access_key: (( prune ))
      driver:      git
      uri:         git@github.com:gstackio/gk-pipelines-compass.git
      branch:      master
      file:        (( concat "versions/" meta.pipeline ))
      private_key: ((github-private-key))
      git_user:    "((git-commit-name)) <((git-commit-email))>"
